
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
kind: pipeline
type: kubernetes

# resource requests are defined on the pipeline level
resources:
  requests:
    cpu: 6000
    memory: 6000MiB

steps:
  - name: en
    image: alpine
    commands:
      - echo hello
    resources:
      # resource limits are defined for each step
      limits:
        cpu: 5000
        memory: 5000MiB

  - name: es
    image: alpine
    commands:
      - echo hola

  - name: fr
    image: alpine
    commands:
      - echo bonjour
